import {test,expect} from '@playwright/test';
import {fixture} from './fixtures';
test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus){await page.screenshot({path:info.outputPath('failure.png'),fullPage:true}).catch(()=>{});console.log(await page.evaluate(()=>({viewport:[innerWidth,innerHeight],bodyRect:document.body.getBoundingClientRect().toJSON(),heading:[...document.querySelectorAll('h1')].map(e=>({text:e.textContent,style:getComputedStyle(e).display,rect:e.getBoundingClientRect().toJSON()})),bodyStyle:getComputedStyle(document.body).display})).catch(()=>({closed:true})));}});

test('real HTTP: absent infrastructure fails closed; no sample family or iframe',async({page,request})=>{
 const session=await request.get('/api/session');expect(await session.json()).toEqual({role:null,configured:false});
 const denied=await request.get('/api/child/player?videoId=10000000-0000-4000-8000-000000000001');expect(denied.status()).toBe(503);
 const cross=await request.post('/api/parent/videos',{headers:{Origin:'https://evil.test'},data:{}});expect(cross.status()).toBe(403);
 await page.goto('/watch/player/10000000-0000-4000-8000-000000000001');await expect(page.getByRole('heading',{name:'This video is unavailable'})).toBeVisible();expect(await page.locator('iframe').count()).toBe(0);
});
test('real HTTP: public entry, protected parent redirect, and unknown page',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Their favorites. Your peace of mind.'})).toBeVisible();await page.goto('/parent/dashboard');await expect(page).toHaveURL(/\/login$/);await page.goto('/this-page-does-not-exist');await expect(page.getByRole('heading',{name:'This page isn’t here.'})).toBeVisible();});
test('synthetic UI: parent navigation covers management, inbox, and independent access',async({page})=>{await fixture(page,'parent');await page.goto('/parent/dashboard');await expect(page.getByRole('heading',{name:'A little watching. A lot of curiosity.'})).toBeVisible();await page.getByRole('link',{name:'Children',exact:true}).click();await expect(page.getByRole('heading',{name:'Miri',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Eli',exact:true})).toBeVisible();await page.getByRole('link',{name:/Inbox/}).click();await expect(page.getByRole('heading',{name:'Lego trains'})).toBeVisible();await page.getByRole('link',{name:'Find a video'}).click();await expect(page.getByLabel('Video, show, creator or topic')).toHaveValue('Lego trains');});
test('synthetic UI: child searches local library and asks parent on no match',async({page})=>{const changes=await fixture(page,'child');await page.goto('/watch/home');await expect(page.getByRole('heading',{name:/Ari/})).toBeVisible();const search=page.getByPlaceholder('Try a video, show, or topic');await search.fill('no matching dinosaur');await expect(page.getByRole('heading',{name:'No videos found yet'})).toBeVisible();await page.locator('.empty').getByRole('button',{name:'Ask Parent',exact:true}).click();await expect(page.getByRole('heading',{name:'Ask Parent',exact:true})).toBeVisible();await page.getByRole('button',{name:'Send to Parent'}).click();await expect(page.getByRole('heading',{name:'Your request is on its way!'})).toBeVisible();expect(changes.some(c=>c.path==='/api/child/requests'&&c.body.message.includes('dinosaur'))).toBe(true);});
test('synthetic UI: mobile and tablet pages fit viewport',async({page})=>{await fixture(page,'parent');for(const width of [390,768,1024]){await page.setViewportSize({width,height:900});await page.goto('/parent/children');await expect(page.getByRole('heading',{name:'Their space. Your peace of mind.'})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);expect(overflow).toBe(false);} });
