-- Preserve historical tables and approvals. All access is via authenticated server routes.
alter table public.parents add column if not exists auth_user_id uuid unique references auth.users(id);
alter table public.parents add column if not exists family_code text unique default encode(gen_random_bytes(12),'hex');
alter table public.profiles add column if not exists experience_mode text not null default 'standard' check (experience_mode in ('simple','standard'));
alter table public.videos add column if not exists made_for_kids boolean;
create table public.family_videos(parent_id uuid references public.parents(id) on delete cascade,video_id uuid references public.videos(id) on delete cascade,tags text[] not null default '{}',created_at timestamptz not null default now(),primary key(parent_id,video_id));
insert into public.family_videos(parent_id,video_id) select distinct parent_id,video_id from public.profile_video_assignments where removed_at is null on conflict do nothing;
create table public.child_sessions(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,token_hash text not null unique,created_at timestamptz not null default now(),expires_at timestamptz not null,revoked_at timestamptz,last_progress_at timestamptz);
create table public.collections(id uuid primary key default gen_random_uuid(),parent_id uuid not null references public.parents(id) on delete cascade,title text not null,description text,video_ids uuid[] not null default '{}',created_at timestamptz not null default now());
create table public.child_requests(id uuid primary key default gen_random_uuid(),parent_id uuid not null references public.parents(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,kind text not null check(kind in ('video','show','creator','topic')),message text not null check(length(message) between 1 and 200),status text not null default 'pending' check(status in ('pending','resolved','dismissed')),created_at timestamptz not null default now());
create table public.viewing_events(id uuid primary key default gen_random_uuid(),parent_id uuid not null references public.parents(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,video_id uuid not null references public.videos(id) on delete cascade,watched_seconds integer not null check(watched_seconds between 0 and 60),created_at timestamptz not null default now());
create index viewing_events_family_date on public.viewing_events(parent_id,created_at);
create table public.login_limits(key text primary key,window_started timestamptz not null default now(),attempts integer not null default 1);
-- Deny secrets and all direct client data access. Service role only after route authorization.
do $$ declare t text; begin foreach t in array array['parents','profiles','videos','profile_video_assignments','watch_progress','youtube_search_cache','youtube_search_logs','audit_events','family_videos','child_sessions','collections','child_requests','viewing_events','login_limits'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant all on public.%I to service_role',t); end loop; end $$;
create function public.wn_rate_limit(p_key text,p_limit integer,p_seconds integer) returns boolean language plpgsql security invoker set search_path=public as $$ declare n integer; begin insert into login_limits(key) values(p_key) on conflict(key) do update set attempts=case when login_limits.window_started < now()-make_interval(secs=>p_seconds) then 1 else login_limits.attempts+1 end,window_started=case when login_limits.window_started < now()-make_interval(secs=>p_seconds) then now() else login_limits.window_started end returning attempts into n; return n<=p_limit; end $$;
create function public.wn_approve_videos(p_parent uuid,p_videos uuid[],p_profiles uuid[],p_tags text[],p_collection uuid) returns void language plpgsql security invoker set search_path=public as $$ declare v uuid; c uuid; begin if exists(select 1 from unnest(p_profiles) x where not exists(select 1 from profiles where id=x and parent_id=p_parent and archived_at is null)) then raise exception 'Invalid profiles'; end if; if p_collection is not null and not exists(select 1 from collections where id=p_collection and parent_id=p_parent) then raise exception 'Invalid collection'; end if; foreach v in array p_videos loop insert into family_videos(parent_id,video_id,tags) values(p_parent,v,p_tags) on conflict(parent_id,video_id) do update set tags=excluded.tags; foreach c in array p_profiles loop insert into profile_video_assignments(parent_id,profile_id,video_id,approved_by_parent_id) values(p_parent,c,v,p_parent) on conflict(profile_id,video_id) where removed_at is null do nothing; end loop; end loop; if p_collection is not null then update collections set video_ids=array(select distinct unnest(video_ids||p_videos)) where id=p_collection and parent_id=p_parent; end if; end $$;
create function public.wn_assign_video(p_parent uuid,p_video uuid,p_profiles uuid[],p_tags text[]) returns void language plpgsql security invoker set search_path=public as $$ declare c uuid; begin if not exists(select 1 from family_videos where parent_id=p_parent and video_id=p_video) then raise exception 'Not approved'; end if; if exists(select 1 from unnest(p_profiles) x where not exists(select 1 from profiles where id=x and parent_id=p_parent and archived_at is null)) then raise exception 'Invalid profiles'; end if; update profile_video_assignments set removed_at=now() where parent_id=p_parent and video_id=p_video and removed_at is null and not(profile_id=any(p_profiles)); foreach c in array p_profiles loop insert into profile_video_assignments(parent_id,profile_id,video_id,approved_by_parent_id) values(p_parent,c,p_video,p_parent) on conflict(profile_id,video_id) where removed_at is null do nothing; end loop; if p_tags is not null then update family_videos set tags=p_tags where parent_id=p_parent and video_id=p_video; end if; end $$;
create function public.wn_remove_video(p_parent uuid,p_video uuid) returns void language plpgsql security invoker set search_path=public as $$ begin update profile_video_assignments set removed_at=now() where parent_id=p_parent and video_id=p_video and removed_at is null; delete from family_videos where parent_id=p_parent and video_id=p_video; update collections set video_ids=array_remove(video_ids,p_video) where parent_id=p_parent; end $$;
create function public.wn_record_progress(p_session uuid,p_video uuid,p_current integer,p_watched integer,p_completed boolean) returns void language plpgsql security invoker set search_path=public as $$ declare s child_sessions; p profiles; v videos; seconds integer; begin select * into s from child_sessions where id=p_session and revoked_at is null and expires_at>now() for update; if not found then raise exception 'Session expired'; end if; select * into p from profiles where id=s.profile_id and archived_at is null; if not found then raise exception 'Profile unavailable'; end if; perform 1 from profile_video_assignments where parent_id=p.parent_id and profile_id=p.id and video_id=p_video and removed_at is null for share; if not found then raise exception 'Not assigned'; end if; select * into v from videos where id=p_video; if v.availability_status <> 'available' or v.embeddable_status <> 'embeddable' then raise exception 'Video unavailable'; end if; if v.made_for_kids is distinct from false then return; end if; seconds=least(greatest(p_watched,0),60,greatest(0,floor(extract(epoch from now()-coalesce(s.last_progress_at,s.created_at)))::integer)); insert into watch_progress(profile_id,video_id,current_time_seconds,duration_seconds,completed_at) values(p.id,p_video,least(greatest(p_current,0),v.duration_seconds),v.duration_seconds,case when p_completed and p_current>=v.duration_seconds*.95 then now() else null end) on conflict(profile_id,video_id) do update set current_time_seconds=excluded.current_time_seconds,duration_seconds=excluded.duration_seconds,completed_at=excluded.completed_at,updated_at=now(); if seconds>0 then insert into viewing_events(parent_id,profile_id,video_id,watched_seconds) values(p.parent_id,p.id,p_video,seconds); end if; update child_sessions set last_progress_at=now() where id=s.id; end $$;
revoke all on function public.wn_rate_limit(text,integer,integer),public.wn_approve_videos(uuid,uuid[],uuid[],text[],uuid),public.wn_assign_video(uuid,uuid,uuid[],text[]),public.wn_remove_video(uuid,uuid),public.wn_record_progress(uuid,uuid,integer,integer,boolean) from public,anon,authenticated;
grant execute on function public.wn_rate_limit(text,integer,integer),public.wn_approve_videos(uuid,uuid[],uuid[],text[],uuid),public.wn_assign_video(uuid,uuid,uuid[],text[]),public.wn_remove_video(uuid,uuid),public.wn_record_progress(uuid,uuid,integer,integer,boolean) to service_role;
-- Household integrity remains enforced if server code makes an incorrect write.
alter table public.profiles add constraint profiles_id_parent_unique unique(id,parent_id);
alter table public.profile_video_assignments add constraint assignments_profile_household_fk foreign key(profile_id,parent_id) references public.profiles(id,parent_id) not valid;
alter table public.profile_video_assignments add constraint assignments_approver_household_check check(approved_by_parent_id=parent_id) not valid;
alter table public.child_requests add constraint requests_profile_household_fk foreign key(profile_id,parent_id) references public.profiles(id,parent_id);
alter table public.viewing_events add constraint events_profile_household_fk foreign key(profile_id,parent_id) references public.profiles(id,parent_id);
